from pathlib import Path

path = Path('/home/ubuntu/jobpick-audit/tools/index.html')
text = path.read_text()
old = "const instructions='Rewrite the entire CV from scratch as a final application-ready CV tailored to '+roleContext+'. '+(jobDescription?'Use this vacancy description as the targeting reference: '+jobDescription+'. ':'')+'Preserve every factual detail from the source, reorganize all relevant sections, prioritize role-relevant achievements and skills, and return only the finished CV. Do not return analysis, explanations, markdown fences, or any section named EDITOR NOTES.';"
new = "const instructions='You are an expert CV writer, ATS optimization specialist, recruiter, and hiring manager. Regenerate the complete CV for the target role using the source CV and vacancy description. First analyze the vacancy internally: identify the job title, core responsibilities, required and preferred skills, ATS keywords, qualifications, and recruiter priorities. Then analyze the source CV internally and classify evidence as highly relevant, transferable, or low relevance. Match each important requirement only to truthful evidence from the source CV. Rewrite the CV from scratch as a polished, ATS-friendly, application-ready document. Keep real employers, job titles, dates, education, certifications, languages, tools, responsibilities, and measurable achievements; preserve legitimate numbers. Rephrase and reorganize for relevance, use strong action verbs and concise achievement-focused bullets, and naturally include supported terminology without keyword stuffing. Never invent experience, employers, titles, dates, responsibilities, achievements, KPIs, certifications, technologies, education, languages, or qualifications. If a required item is missing or unclear, omit it rather than guessing. Use a targeted 3–5 line summary, a prioritized skills section with truthful categories, professional experience, education, certifications, and languages only when useful. Choose one page for early-career candidates and up to two pages for experienced candidates; do not remove important evidence just to force one page. Check spelling, grammar, dates, consistency, ATS readability, and recruiter scanability. The final output must contain only the finished CV, with no analysis, ATS score, recruiter review, application-gap commentary, markdown fences, placeholders, or section named EDITOR NOTES. Any missing requirements must be silently omitted from the CV and must not be fabricated. '+(jobDescription?'Vacancy description: '+jobDescription+'. ':'')+'Target role: '+(roleContext||'the target role')+'.';"
if old not in text:
    raise SystemExit('original instruction string not found')
text = text.replace(old, new, 1)
old_check = "function cleanGeneratedCv(text){\n  let value=String(text||'').replace(/```(?:text|markdown)?/gi,'').replace(/```/g,'').trim();\n  const notes=value.search(/^###\\s*EDITOR NOTES\\b/im);\n  if(notes>=0)value=value.slice(0,notes).trim();\n  return value;\n}"
new_check = "function cleanGeneratedCv(text){\n  let value=String(text||'').replace(/```(?:text|markdown)?/gi,'').replace(/```/g,'').trim();\n  const notes=value.search(/^###\\s*EDITOR NOTES\\b/im);\n  if(notes>=0)value=value.slice(0,notes).trim();\n  return value;\n}\nfunction assessCvReadiness(text){\n  const value=String(text||'');\n  const hasContact=/(?:@|\\+?\\d[\\d ()-]{6,}|linkedin\\.com|https?:\\/\\/)/i.test(value);\n  const hasSummary=/(?:professional summary|summary|profile|objective)/i.test(value);\n  const hasExperience=/(?:professional experience|work experience|experience|employment history)/i.test(value);\n  const hasSkills=/(?:core skills|technical skills|skills|tools|systems)/i.test(value);\n  const hasEducation=/(?:education|academic background|degree|bachelor|master)/i.test(value);\n  const missing=[];\n  if(!hasContact)missing.push('contact information');\n  if(!hasSummary)missing.push('professional summary');\n  if(!hasExperience&&!hasEducation)missing.push('experience or education');\n  if(!hasSkills)missing.push('skills');\n  return {ready:missing.length===0,missing};\n}"
if old_check not in text:
    raise SystemExit('cleanGeneratedCv block not found')
text = text.replace(old_check, new_check, 1)
old_preview = "cvPreview.innerHTML='<strong>Final tailored CV preview</strong><pre style=\"white-space:pre-wrap;font:inherit;margin:10px 0 0\">'+generatedCvText.replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</pre>';trackCv('cv_generation_success',{template:document.getElementById('cvTemplate').value});setSecureMessage('<strong>Complete tailored CV ready.</strong><br>Review the final application-ready version before downloading the PDF.');"
new_preview = "const readiness=assessCvReadiness(generatedCvText);cvPreview.innerHTML='<strong>Final tailored CV preview</strong><pre style=\"white-space:pre-wrap;font:inherit;margin:10px 0 0\">'+generatedCvText.replace(/&/g,'&amp;').replace(/</g,'&lt;')+'</pre>';trackCv('cv_generation_success',{template:document.getElementById('cvTemplate').value,ready_to_apply:readiness.ready?'yes':'review'});setSecureMessage(readiness.ready?'<strong>Complete application-ready CV ready.</strong><br>Review the final version before downloading the PDF.':'<strong>CV generated, but needs review before applying.</strong><br>Missing or unclear sections: '+readiness.missing.join(', ')+'.');"
if old_preview not in text:
    raise SystemExit('preview success block not found')
text = text.replace(old_preview, new_preview, 1)
path.write_text(text)
